### ISSUE TITLE
wine: accServer.exe missing.

### ISSUE THREAD

**Issue by HendrikRoth** [grimsi/accservermanager#10]
The newly created docker container (managed by accservermanager) with the docker image grimsi/accserver:latest seams not to find the accServer.exe file.

```
wine: cannot find L"C:\\windows\\system32\\accServer.exe"
```
![2019-05-18 16_21_17-Window](https://user-images.githubusercontent.com/68462/57971032-00a7fb00-7989-11e9-975b-c3c63afb1a39.jpg)

**Comment by HendrikRoth** [comment]
the content of the folder of /opt/server (instances folder) looks like this:

![2019-05-18 16_24_56-Window](https://user-images.githubusercontent.com/68462/57971065-8d52b900-7989-11e9-8fdf-bd9a63a464df.jpg)

**Comment by grimsi** [comment]
Looks like my backend has problems mounting the accServer.exe into the sibling container for your instance. Does this happen with every instance you create?

**Comment by HendrikRoth** [comment]
Jepp, for every instance the same issue.

**Comment by HendrikRoth** [comment]
you can't mount /instances/5ce01333e21b840008a0ce5e this way how your manager does this when you are using docker volumes. /instances in this case is linked as a host-directory, but they are located in a docker volume.

**Comment by HendrikRoth** [comment]
to reproduce this issue, please mount /opt/server in accservermanager as a docker volume, this should make this issue clear.

**Comment by grimsi** [comment]
Yeah, docker volumes are not supported for the backend you need to mount the directory directly from the host.
I will take a look at how easy it is to implement support, maybe it will be a feature for the next release.

**Comment by HendrikRoth** [comment]
tried now to bind the directory for /opt/server to a host-system directory.

the problem is that the folder /instances (with the binded folder) is not mounted to the new created instance, therefore he can't find the accServer.exe

**Comment by grimsi** [comment]
I only had this problem with Docker Desktop on Windows, weird to see it on Ubuntu.
Anyway can you give me the logs from the backend? I will take a look at it

**Comment by HendrikRoth** [comment]
the err.log of accservermanager is empty, the interface thinks also that the instance is working fine.

**Comment by grimsi** [comment]
The backend does not actively monitor the state of the container it just checks if the container started and then shows "running" but it does not check if the server executable itself was able to start.
Please refer to [this comment](https://github.com/grimsi/accservermanager/issues/4#issuecomment-482083406) on how to obtain the logfiles from my application.

**Comment by grimsi** [comment]
Does this problem still exist? If so, please send me the logs so I can assist you, otherwise just comment and I will close this issue :)

**Comment by HendrikRoth** [comment]
Yes, still exists. I'll post logs the next days :-)
