### ISSUE TITLE
Will the ACC Server Manager support the new tracks on full release or will it need an update?

### ISSUE THREAD

**Issue by GazCBG** [grimsi/accservermanager#12]
With ACC full version due to be released sometime today, will the Server Manager support the new tracks out the box or will there be an update needed for this?

**Comment by grimsi** [comment]
There will be an updated needed for this.
Unfortunately Kunos did not release an official documentation for the 1.0 server configuration features so I have to wait until I get my hands on something like this.
You can check the current state [here](https://github.com/grimsi/accservermanager/issues/11)
