### ISSUE TITLE
Support for dedicated server when native Linux binaries are released

### ISSUE THREAD

**Issue by CptChaos** [grimsi/accservermanager#14]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support for the dedicated Linux server when the native version get's released

**Describe alternatives you've considered**
At the moment the instance runs in a docker container with wine

**Comment by grimsi** [comment]
Unfortunately I don't know if we will ever get a native Linux build, nothing has been confirmed yet. But if we do get one I will ditch wine and use a smaller docker container (probably Alpine based if that works)

**Comment by surtic86** [comment]
I opened a Forum Post in December 2018 on the Official Forum but haven't got any Response from the Dev's.

https://www.assettocorsa.net/forum/index.php?threads/dedicated-server-for-linux.54083/#post-1053753

**Comment by surtic86** [comment]
Answer from Kunos: They have no Plans for a Linux Server Binary.

https://www.assettocorsa.net/forum/index.php?threads/dedicated-server-for-linux.54083/page-2#post-1077422

**Comment by CptChaos** [comment]
Then this issue can be closed, for now.

I think it's a pity though, but I guess we'll  have to live with it.
