### ISSUE TITLE
Server in Docker keeps starting wine in a defunct state?

### ISSUE THREAD

**Issue by CptChaos** [grimsi/accservermanager#20]
**Describe the bug**
When doing a clean install, for some reason a server starts with wine in a defunct state and it doesn't start the server at all. Despite the correct port forwardings I don't see my created server appear in-game in the serverbrowser / -list.

**To Reproduce**
Make a clean install of the docker image

**Expected behavior**
That wine on the server actually starts and doesn't start in a defunct state so I can actually join my created server from the game.

**Screenshots**
Have none.

**Desktop (please complete the following information):**
Debian 9 VM, 4GB RAM, 50GB diskspace.
Servers running in Docker, where wine starts 'defunct'.

**Additional context**
Maybe it's not a bug, but just something I have to set-up correctly, but don't know what as I am not a pro at Docker.

**Comment by grimsi** [comment]
Can you provide the log output from the server container?

**Comment by CptChaos** [comment]
Will do this as soon as possible when I have time, won't be in or before this weekend.

**Comment by grimsi** [comment]
No worries, I wont be available the next two weeks, but I will take a look at your problem after it

**Comment by CptChaos** [comment]
Hmmm, not sure what did it to be honest. I made a completely fresh install (including the VM) and it worked right away, so I can't reproduce it and therefor close the issue.
