### ISSUE TITLE
Docker file supervisord.conf missing

### ISSUE THREAD

**Issue by Danielvr** [grimsi/accservermanager#26]
**Describe the bug**
I want to update this project to work with newer versions and that works great I only have a problem with the docker image.

I have your docker file from this location. https://hub.docker.com/r/grimsi/accservermanager/dockerfile but I'm missing this file ADD     supervisord.conf /etc/supervisor.conf
Do you still have the file and can you share it. Than I hope I can update the project so that it will work again.

Daniel

**Comment by grimsi** [comment]
Hi, you can find everything you need to build the container here: https://github.com/grimsi/accservermanager-container
