### ISSUE TITLE
Run servers as user and not root?

### ISSUE THREAD

**Issue by GazCBG** [grimsi/accservermanager#7]
Is there away to run the servers as a user and not as root user, due to security?
I know docker supports users but never seem to work for me.

**Comment by grimsi** [comment]
You have to add the user that should be allowed to run docker to the "docker" group. See [here](https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo)

**Comment by GazCBG** [comment]
I looked at that on the docker site and the docker user/group from what I read has the similar privileges as root.

**Comment by grimsi** [comment]
There is no other way afaik.You can't really run docker without root

**Comment by GazCBG** [comment]
I know docker needs root but is there no way to run the container as a user without root or similar privileges?

**Comment by grimsi** [comment]
I checked to docker docs and did not find a way, but feel free to look it up yourself maybe you have more luck
