### ISSUE TITLE
Can't select "Version" during creating a new server

### ISSUE THREAD

**Issue by HendrikRoth** [grimsi/accservermanager#9]
Hello,

i am using your latest docker image to start the accservermanager and mounted my accServer.exe to the /opt/server directory. accservermanager starts, i can add events.. but starting a new server, i cannot select any "version".

What did i miss here? Thanks!

### The info tab gives following informations:

System Information
Backend version: 1.0.0

Metrics: enabled

Supported ACC server versions:
Servers online: 0

**Comment by HendrikRoth** [comment]
![2019-05-18 15_17_51-Window](https://user-images.githubusercontent.com/68462/57970322-2aa8ef80-7980-11e9-9cbe-3aca5f0d8842.jpg)

**Comment by grimsi** [comment]
Does your mounted server folder look like [this](https://github.com/grimsi/accservermanager/wiki/Set-up-the-server-executable-folder)?

**Comment by HendrikRoth** [comment]
Sorry my folder structure was wrong, is working now. thank you!
